CREATE TABLE IF NOT EXISTS org_service_accounts (
org_id BIGINT PRIMARY KEY REFERENCES orgs(id) ON DELETE CASCADE,
sub TEXT NOT NULL UNIQUE REFERENCES users(sub) ON DELETE CASCADE,
created_by TEXT,
created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
