"""Registry declaration of the `leexi` connector.

Single home of its entry: `providers/__init__.py` AGGREGATES it (it does not
describe it). See `providers/_model.py` for the `Connector` contract.
"""
from __future__ import annotations

from ._model import CredentialField, _c

# leexi: conversation intelligence (calls, transcripts, meeting notes)
# — same family as `fireflies`, `grain` and `granola`, hence the Knowledge
# category and the same BYO regime.
#
# ⚠️ **Basic** auth with TWO fields (`KEY_ID` + `KEY_SECRET`), not a single key.
# Hence `secret_kind="fields"` and **not** `keyed`: resolution goes through
# `access.resolve_credential_fields`, which returns both fields (`resolve_api_key`
# would only return one). Both are generated on the Leexi side in Settings → Company
# Settings → API Keys, and require an ADMIN account — it is not a key an
# ordinary user can create for themselves.
#
# `key_id` is declared NOT secret: it is the identifier Leexi shows in its
# key list, and making it readable lets you see WHICH one is set without
# ever exposing the secret that goes with it — same split as `posthog` between its key
# and its host.
#
# ⚠️ **A new key only carries `read_calls`.** Everything else — and namely
# `write_users`/`write_teams`, which commit the customer's BILLED LICENSES —
# must be granted explicitly by a Leexi admin. The connector cannot
# get around that notch and does not try: the write tools exist, upstream
# answers 403 if the key does not carry them, and the message says so.
#
# Strict BYOK (`byo_user` + `byo_org`, no platform mode): these are the customer's
# recorded conversations, there cannot be a shared oto key that would give
# one party the other's calls.
CONNECTOR = _c(
    "leexi", ["leexi"], auth_modes={"byo_user", "byo_org"},
    secret_kind="fields",
    credential_fields=(
        CredentialField(
            "key_id", "API Key ID", secret=False,
            help="Key identifier, generated in Leexi → Settings → "
                 "Company Settings → API Keys (admin account required)."),
        CredentialField(
            "key_secret", "Key Secret", secret=True,
            help="The associated secret, shown ONLY ONCE when the key is "
                 "created on the Leexi side."),
    ),
    label="Leexi",
    help="recorded calls and meetings, transcripts, notes, teams — "
         "the organization's conversation intelligence",
    href="https://www.leexi.ai",
)

CATEGORY = "Knowledge"
PUBLISHER = "Leexi"
LOGO_DOMAIN = "leexi.ai"

DESCRIPTION = (
    "The calls and meetings recorded by Leexi: transcripts, summary notes, "
    "teams — same family as Fireflies, Grain and Granola. "
    "Authentication with two fields generated by an admin account, in Settings "
    "→ API Keys."
)
